#!/bin/ash

set -e

HOME='/root'
version='1.9.3.1'
srcdir="ngx_openresty-${version}"
tarball="${srcdir}.tar.gz"
url="https://openresty.org/download/${tarball}"
openresty_dir='/usr/local/openresty'
logdir="${openresty_dir}/nginx/logs"

cd
rm -vf run

apk --update add --virtual builddeps \
  curl \
  gcc \
  make \
  musl-dev \
  ncurses-dev \
  openssl-dev \
  pcre-dev \
  perl \
  readline-dev

curl -LO "${url}"
tar -xzvf "${tarball}"

cd "${srcdir}"
./configure \
  --with-ipv6 \
  --with-pcre-jit
make
make install

apk del builddeps

apk add \
  libgcc \
  pcre

rm -rvf \
  /var/cache/apk* \
  ${HOME}/${srcdir} \
  ${HOME}/${tarball}

ln -svf /dev/stdout "${logdir}/access.log"
ln -svf /dev/stderr "${logdir}/error.log"

set +e
